[package]
name = "razel"
version = "0.1.0"
authors = ["Stefan Reuschl <stefan.reuschl@gmail.com>"]
edition = "2021"
description = "chained commands/tasks executor with caching"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.53"
base16ct = { version = "0.1", features = ["alloc"] }
clap = { version = "3.1.6", features = ["derive"] }
csv = "1.1.6"
itertools = "0.10.3"
log = "0.4.14"
num_cpus = "1.8.0"
prost = "0.10"
prost-types = "0.10"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sha2 = "0.10"
simplelog = "0.11.2"
tokio = { version = "1.18.2", features = ["full"] }

[build-dependencies]
prost-build = "0.10"
tonic-build = "0.7"

[dev-dependencies]
approx = "0.5.1"
env_logger = "0.9.0"
serial_test = "0.6.0"
